-- AI Chief of Staff Database Schema
-- SQLite schema with full-text search support

-- ============================================================================
-- Core Data Tables
-- ============================================================================

-- Emails from Gmail
CREATE TABLE IF NOT EXISTS emails (
    id TEXT PRIMARY KEY,
    thread_id TEXT NOT NULL,
    from_address TEXT NOT NULL,
    to_addresses TEXT NOT NULL,  -- JSON array
    cc_addresses TEXT,  -- JSON array
    subject TEXT,
    body TEXT,
    snippet TEXT,
    timestamp DATETIME NOT NULL,
    labels TEXT,  -- JSON array
    is_flagged BOOLEAN DEFAULT 0,
    is_read BOOLEAN DEFAULT 0,
    has_attachments BOOLEAN DEFAULT 0,
    priority_score REAL DEFAULT 0.0,
    requires_response BOOLEAN DEFAULT 0,
    suggested_reply TEXT,
    metadata TEXT,  -- JSON
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Calendar events from Google Calendar
CREATE TABLE IF NOT EXISTS calendar_events (
    id TEXT PRIMARY KEY,
    summary TEXT NOT NULL,
    description TEXT,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    attendees TEXT,  -- JSON array
    organizer TEXT,
    location TEXT,
    meeting_link TEXT,
    status TEXT,
    is_recurring BOOLEAN DEFAULT 0,
    recurrence_rule TEXT,
    extracted_action_items TEXT,  -- JSON array
    preparation_notes TEXT,
    follow_up_tasks TEXT,  -- JSON array
    metadata TEXT,  -- JSON
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Coda documents and their content
CREATE TABLE IF NOT EXISTS coda_documents (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    doc_type TEXT,  -- roadmap, okrs, strategy, etc.
    content TEXT,
    last_modified DATETIME,
    modified_by TEXT,
    url TEXT,
    change_summary TEXT,
    key_decisions TEXT,  -- JSON array
    metadata TEXT,  -- JSON
    synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tasks extracted from emails, meetings, and docs
CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    source TEXT NOT NULL,  -- email, calendar, coda
    source_id TEXT,
    priority TEXT DEFAULT 'medium',  -- high, medium, low
    priority_score REAL DEFAULT 0.5,
    due_date DATETIME,
    status TEXT DEFAULT 'pending',  -- pending, in_progress, completed, cancelled
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    completed_at DATETIME,
    context TEXT,  -- Why this matters
    suggested_action TEXT,
    assigned_to TEXT,
    metadata TEXT  -- JSON
);

-- Decisions and their rationale
CREATE TABLE IF NOT EXISTS decisions (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    rationale TEXT,  -- The "why"
    made_on DATETIME NOT NULL,
    made_by TEXT,
    source TEXT,  -- email, meeting, coda
    source_id TEXT,
    impact_areas TEXT,  -- JSON array (e.g., roadmap, team, strategy)
    related_decisions TEXT,  -- JSON array of decision IDs
    is_active BOOLEAN DEFAULT 1,
    superseded_by TEXT,  -- ID of decision that supersedes this one
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Daily briefings
CREATE TABLE IF NOT EXISTS daily_briefings (
    id TEXT PRIMARY KEY,
    date DATE UNIQUE NOT NULL,
    generated_at DATETIME NOT NULL,
    priorities TEXT,  -- JSON array of task IDs
    email_drafts TEXT,  -- JSON array
    meeting_followups TEXT,  -- JSON array
    coda_updates TEXT,  -- JSON array
    delivered BOOLEAN DEFAULT 0,
    delivered_at DATETIME,
    opened BOOLEAN DEFAULT 0,
    opened_at DATETIME,
    feedback_score INTEGER,  -- 1-5 rating
    metadata TEXT,  -- JSON
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Email drafts generated by AI
CREATE TABLE IF NOT EXISTS email_drafts (
    id TEXT PRIMARY KEY,
    original_email_id TEXT NOT NULL,
    suggested_reply TEXT NOT NULL,
    tone TEXT DEFAULT 'professional',
    key_points TEXT,  -- JSON array
    confidence_score REAL,
    used BOOLEAN DEFAULT 0,
    user_feedback TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (original_email_id) REFERENCES emails(id)
);

-- User feedback on AI suggestions
CREATE TABLE IF NOT EXISTS feedback (
    id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,  -- briefing, email_draft, task, etc.
    entity_id TEXT NOT NULL,
    rating INTEGER,  -- 1-5 or thumbs up/down (-1, 1)
    comment TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Sync status tracking
CREATE TABLE IF NOT EXISTS sync_status (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source TEXT NOT NULL,  -- gmail, calendar, coda
    last_sync_time DATETIME NOT NULL,
    last_sync_status TEXT,  -- success, failure, partial
    next_sync_time DATETIME,
    error_message TEXT,
    items_synced INTEGER,
    metadata TEXT,  -- JSON
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Application configuration and state
CREATE TABLE IF NOT EXISTS app_state (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- Full-Text Search Tables (FTS5)
-- ============================================================================

-- Full-text search for emails
CREATE VIRTUAL TABLE IF NOT EXISTS emails_fts USING fts5(
    id UNINDEXED,
    subject,
    body,
    snippet,
    from_address,
    content=emails,
    content_rowid=rowid
);

-- Full-text search for Coda documents
CREATE VIRTUAL TABLE IF NOT EXISTS coda_documents_fts USING fts5(
    id UNINDEXED,
    name,
    content,
    content=coda_documents,
    content_rowid=rowid
);

-- Full-text search for tasks
CREATE VIRTUAL TABLE IF NOT EXISTS tasks_fts USING fts5(
    id UNINDEXED,
    title,
    description,
    context,
    content=tasks,
    content_rowid=rowid
);

-- ============================================================================
-- Indexes for Performance
-- ============================================================================

-- Email indexes
CREATE INDEX IF NOT EXISTS idx_emails_timestamp ON emails(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_emails_thread ON emails(thread_id);
CREATE INDEX IF NOT EXISTS idx_emails_priority ON emails(priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_emails_flagged ON emails(is_flagged, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_emails_unread ON emails(is_read, timestamp DESC);

-- Calendar event indexes
CREATE INDEX IF NOT EXISTS idx_calendar_start ON calendar_events(start_time);
CREATE INDEX IF NOT EXISTS idx_calendar_end ON calendar_events(end_time);
CREATE INDEX IF NOT EXISTS idx_calendar_status ON calendar_events(status);

-- Task indexes
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_source ON tasks(source, source_id);

-- Decision indexes
CREATE INDEX IF NOT EXISTS idx_decisions_made_on ON decisions(made_on DESC);
CREATE INDEX IF NOT EXISTS idx_decisions_active ON decisions(is_active);

-- Daily briefing indexes
CREATE INDEX IF NOT EXISTS idx_briefings_date ON daily_briefings(date DESC);

-- Sync status indexes
CREATE INDEX IF NOT EXISTS idx_sync_source ON sync_status(source, last_sync_time DESC);

-- ============================================================================
-- Triggers for FTS5 Synchronization
-- ============================================================================

-- Trigger to update emails FTS on insert
CREATE TRIGGER IF NOT EXISTS emails_fts_insert AFTER INSERT ON emails BEGIN
    INSERT INTO emails_fts(id, subject, body, snippet, from_address)
    VALUES (new.id, new.subject, new.body, new.snippet, new.from_address);
END;

-- Trigger to update emails FTS on update
CREATE TRIGGER IF NOT EXISTS emails_fts_update AFTER UPDATE ON emails BEGIN
    DELETE FROM emails_fts WHERE id = old.id;
    INSERT INTO emails_fts(id, subject, body, snippet, from_address)
    VALUES (new.id, new.subject, new.body, new.snippet, new.from_address);
END;

-- Trigger to update emails FTS on delete
CREATE TRIGGER IF NOT EXISTS emails_fts_delete AFTER DELETE ON emails BEGIN
    DELETE FROM emails_fts WHERE id = old.id;
END;

-- Trigger to update coda_documents FTS on insert
CREATE TRIGGER IF NOT EXISTS coda_documents_fts_insert AFTER INSERT ON coda_documents BEGIN
    INSERT INTO coda_documents_fts(id, name, content)
    VALUES (new.id, new.name, new.content);
END;

-- Trigger to update coda_documents FTS on update
CREATE TRIGGER IF NOT EXISTS coda_documents_fts_update AFTER UPDATE ON coda_documents BEGIN
    DELETE FROM coda_documents_fts WHERE id = old.id;
    INSERT INTO coda_documents_fts(id, name, content)
    VALUES (new.id, new.name, new.content);
END;

-- Trigger to update coda_documents FTS on delete
CREATE TRIGGER IF NOT EXISTS coda_documents_fts_delete AFTER DELETE ON coda_documents BEGIN
    DELETE FROM coda_documents_fts WHERE id = old.id;
END;

-- Trigger to update tasks FTS on insert
CREATE TRIGGER IF NOT EXISTS tasks_fts_insert AFTER INSERT ON tasks BEGIN
    INSERT INTO tasks_fts(id, title, description, context)
    VALUES (new.id, new.title, new.description, new.context);
END;

-- Trigger to update tasks FTS on update
CREATE TRIGGER IF NOT EXISTS tasks_fts_update AFTER UPDATE ON tasks BEGIN
    DELETE FROM tasks_fts WHERE id = old.id;
    INSERT INTO tasks_fts(id, title, description, context)
    VALUES (new.id, new.title, new.description, new.context);
END;

-- Trigger to update tasks FTS on delete
CREATE TRIGGER IF NOT EXISTS tasks_fts_delete AFTER DELETE ON tasks BEGIN
    DELETE FROM tasks_fts WHERE id = old.id;
END;

-- Trigger to update updated_at timestamp on emails
CREATE TRIGGER IF NOT EXISTS emails_updated_at AFTER UPDATE ON emails BEGIN
    UPDATE emails SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Trigger to update updated_at timestamp on calendar_events
CREATE TRIGGER IF NOT EXISTS calendar_events_updated_at AFTER UPDATE ON calendar_events BEGIN
    UPDATE calendar_events SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Trigger to update updated_at timestamp on tasks
CREATE TRIGGER IF NOT EXISTS tasks_updated_at AFTER UPDATE ON tasks BEGIN
    UPDATE tasks SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Trigger to update updated_at timestamp on decisions
CREATE TRIGGER IF NOT EXISTS decisions_updated_at AFTER UPDATE ON decisions BEGIN
    UPDATE decisions SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- ============================================================================
-- Initial Data
-- ============================================================================

-- Insert initial app state
INSERT OR IGNORE INTO app_state (key, value) VALUES ('db_version', '1.0.0');
INSERT OR IGNORE INTO app_state (key, value) VALUES ('initialized_at', datetime('now'));
